import { button } from './components.mjs';
export function fireView() {
  return `<section class="section fire-page"><span class="eyebrow">用好你的竹炭与苹果木</span><h1 class="page-title">先把火用对，再把菜烤香。</h1><p class="intro">竹炭负责持续供热；苹果木负责烟熏风味，不是每道菜都要加木头。</p>
  <div class="fire-warning"><b>只在允许用火的室外开放处使用</b><p>炭火不能进帐篷、车内或其他封闭空间；通风、无烟、炭已发白都不代表没有一氧化碳。炉具抬离可燃地面，旁边备灭火工具；当地禁火时不生火。</p></div>
  <div class="fire-guide-grid"><article class="panel"><span class="guide-number">01 / 竹炭</span><h2>点透再上菜，留一边不放炭</h2><ol><li>用适合食品烧烤的竹炭；不用取暖炭、香薰炭。按照炉具和引火器说明点燃，不向燃烧中的炭补倒酒精或引火液。</li><li>炭充分引燃后，集中放在半边。另一半下方不放炭，用来把厚肉烤熟、避开滴油起火。</li><li>烤网预热并清洁。薄肉串在有炭侧翻烤；厚肉先移到无炭侧加盖，再按需要回到热区上色。</li><li>进风口保持畅通；煎盘不能堵住整炉供氧。按炉具承重和通风要求分区放烤盘，不做密闭“焖炭”。</li></ol><p class="guide-note">炭量取决于炉子大小、风力和时长，不按菜谱数量机械相加。留足引燃时间和备用炭。</p></article>
  <article class="panel"><span class="guide-number">02 / 苹果木</span><h2>少量干木块，轻烟慢慢熏</h2><ol><li>使用无涂层、无防腐处理的食品烟熏苹果木。木块不必泡水；不用树枝捡来的不明木料。</li><li>竹炭稳定后，在热炭边缘放少量木块，先从小块试起。不是铺满木头，也不是让食物直接接触火焰。</li><li>食物放在无炭侧，下面接油盘。盖上炉盖，按炉具说明调进、排气，保持稳定轻烟；不要把风口关死。</li><li>炉温计看炉内温度，探针看食物中心。厚肉按对应配方完成标准烤，不能只盯颜色或分钟数。</li></ol><p class="guide-note">苹果木适合鸡翅、猪肋排、鱼、豆腐等轻甜烟香。奶酪、坚果少熏；蔬果不需要反复补木。</p>${button('看 25 道苹果木烟熏 →','fire-recipes','','btn primary')}</article></div>
  <section class="panel"><h2>同一个炉子，三种做法</h2><div class="method-grid"><article><h3>直接烤</h3><p>食物在热炭上方。适合薄肉串、小块海鲜、蔬菜；勤观察、按配方翻面。</p></article><article><h3>间接烤</h3><p>食物下方无炭，盖炉盖。适合厚肉、整鸡、带骨肉；熟度到位后再上色。</p></article><article><h3>热烟熏</h3><p>间接火加少量苹果木。需要带盖双区炉、炉温计和肉类探针；这里不提供冷熏或常温保存工艺。</p></article></div></section>
  <section class="panel"><h2>这些细节，比多撒一把调料重要</h2><div class="method-grid"><article><h3>先熟，后刷甜酱</h3><p>蜜汁、糖和多数烧烤酱最后薄刷，防止外黑内生。油滴起火时把菜移到无炭侧，不拿火焰当“炭香”。</p></article><article><h3>两把夹子，生熟分开</h3><p>生肉腌汁不直接刷熟食。熟食用干净盘；禽肉中心至少 74℃，肉馅至少 71℃。其他食物看各自做法。</p></article><article><h3>冷链从出发就开始</h3><p>易腐食材保持≤4℃。常温放置累计不要超过2小时，环境超过32℃时不超过1小时；熟食同样适用。</p></article></div></section>
  <details class="panel"><summary>安全与技法依据</summary><div class="source-links"><a href="https://www.weber.com/US/en/blog/tips-techniques/how-to-smoke-on-a-charcoal-grill/weber-29697.html" target="_blank" rel="noopener noreferrer">Weber：炭炉烟熏与双区火</a><a href="https://www.cdc.gov/carbon-monoxide/about/index.html" target="_blank" rel="noopener noreferrer">CDC：一氧化碳预防</a><a href="https://www.foodsafety.gov/food-safety-charts/safe-minimum-internal-temperatures" target="_blank" rel="noopener noreferrer">FoodSafety.gov：安全中心温度</a><a href="https://www.foodsafety.gov/keep-food-safe/4-steps-to-food-safety" target="_blank" rel="noopener noreferrer">FoodSafety.gov：冷链与生熟分离</a></div></details></section>`;
}
