import { safeUrl } from '../engine.mjs';
import { E, button } from './components.mjs';
export function settingsView(ctx) {
    const {db,findRecipe,sourceLinks} = ctx;
    return `<section class="section"><span class="eyebrow">资料与管理</span><h1 class="page-title">配方为什么这样定</h1><p class="intro">旧版40道逐项复核：${db.audit.filter(a => a.status === '合并退役').length}道重复项退役，${db.audit.filter(a => a.status === '重写').length}道实质重写，保留其余并校准。新增${db.recipes.filter(r => !db.audit.some(a => a.newId === r.id)).length}种做法。每张卡都有独特口感、现场动作、材料裁决和来源范围。</p>
 <div class="decision-grid">${db.herbGuide.map(h => `<article class="panel"><h3>${E(h.name)}</h3><p><b>${E(h.decision)}</b></p><p>${E(h.why)}</p><div class="related">${h.recipes.map(id => button(E(findRecipe(id).title), 'detail', `data-id="${id}"`, 'text-btn')).join('')}</div><details><summary>依据</summary><div class="source-links">${sourceLinks(h.sources)}</div></details></article>`).join('')}</div>
 <div class="panel"><h2>如何理解“定稿”</h2>${db.principles.map(t => `<p>${E(t)}</p>`).join('')}</div>
 <details class="panel"><summary>展开旧版40道逐项审查</summary><div class="audit-table">${db.audit.map(a => `<div class="audit-row"><span class="audit-status">${E(a.status)}</span><div><b>${E(a.oldTitle)}</b>${a.newId && findRecipe(a.newId).title !== a.oldTitle ? ` → ${E(findRecipe(a.newId).title)}` : ''}<p>${E(a.reason)}</p>${a.newId ? button('查看定稿', 'detail', `data-id="${a.newId}"`, 'text-btn') : ''}</div></div>`).join('')}</div></details>
 <details class="panel"><summary>研究来源与安全边界 · ${Object.keys(db.sources).length}项</summary><p>食谱来源支持组合/技法；程序中的份量、设备改编与操作安排由本版制定。没有声称在你的炉具上做过实灶试吃。</p>${Object.entries(db.sources).map(([id, s]) => `<div class="source-entry"><a href="${E(safeUrl(s.url))}" target="_blank" rel="noopener noreferrer">${E(s.title)} ↗</a><p>${E(s.scope)}</p></div>`).join('')}</details>
 <div class="panel"><h2>备份、扩展与迁移</h2><p>完整备份包含库存勾选、分类、菜单、笔记、进度及当前菜谱库。源码中的 <code>data/recipes.json</code> 是正式配方库。导入前校验材料、数量、引用和唯一ID；不执行JSON里的代码。旧版菜单可迁移，但旧鲜干配方库不直接沿用。</p><div class="actions">${button('导出完整备份', 'export-backup')}${button('导入完整备份', 'import-backup', '', 'btn ghost')}${button('导出菜谱库', 'export-library', '', 'btn ghost')}${button('导入菜谱库', 'import-library', '', 'btn ghost')}${button('恢复内置库', 'restore-library', '', 'text-btn')}</div><p>导入库会重算材料并清空进度，保留仍存在的选菜ID与笔记。只在本机保存；修改前先导出。</p><p class="muted">浏览器本地文件是否允许自动记忆由浏览器决定。移动端聊天预览器可能禁用脚本；请在浏览器打开，或按源码README通过局域网访问。</p></div></section>`;
}
