import { E, photoHTML } from '../ui/components.mjs';
import { defaultState, buildPlan, recipeView, formatQty } from '../engine.mjs';
import { inventoryCandidates, matchInventory, searchEntries } from '../core/pantry.mjs';
import { paginate } from '../core/pagination.mjs';
import { ownMember, operationValue } from './client.mjs';
export function roomButton(text,action,extra='',cls='btn') {return `<button type="button" class="${cls}" data-room-action="${action}" ${extra}>${text}</button>`;}
export function dateLabel(seconds) {return new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(seconds*1000));}
export function roomPlan(room,db) {return buildPlan(db,{...defaultState(),people:room.settings.people,selected:room.selected,portions:room.settings.portions,order:room.selected,hasFreezer:room.hasFreezer,menuName:`火边房间 ${room.number}`});}
function policy() {return `<p class="room-policy">创建起保留7天，到期关闭并永久停用房号。仅房号、菜单和物资汇总归档至公开GitHub，不含昵称、口令和成员身份。房间期间成员可看见彼此的昵称与选择。</p>`;}
export function lobbyView(c) {
  const creating=c.mode==='create', busy=c.client.status==='joining';
  if(location.protocol==='file:')return `<div class="room-intro"><span class="eyebrow">一起点菜</span><h1>和朋友共用一张菜单。</h1><p>离线文件可个人使用；创建和加入房间需要打开线上网站。</p><a class="btn primary" href="https://furrypant.com/#rooms" target="_blank" rel="noopener noreferrer">在线一起点菜</a></div>`;
  return `<div class="room-intro"><span class="eyebrow">火边 · 一起点菜</span><h1>你带食材，我来点菜。</h1><p>共用一个房号，把大家想吃的、能带的凑在一起。</p></div><div class="room-lobby-grid"><section class="room-entry panel"><div class="room-segments" role="group" aria-label="创建或加入房间">${roomButton('创建房间','mode','data-value="create" aria-pressed="'+creating+'"',creating?'active':'')}${roomButton('加入房间','mode','data-value="join" aria-pressed="'+!creating+'"',!creating?'active':'')}</div><form id="room-entry-form"><label>房间号<input name="number" id="room-number" type="text" inputmode="numeric" pattern="[0-9]{4,12}" minlength="4" maxlength="12" required autocomplete="off" placeholder="例如 001234" value="${E(c.fields.number||'')}"><small>${creating?'自选4—12位数字；不要用手机号。':'输入朋友发来的房号。'}</small></label><label>你的昵称<input name="nickname" id="room-nickname" type="text" maxlength="16" required autocomplete="off" placeholder="让朋友知道是谁" value="${E(c.fields.nickname||'')}"></label><label>${creating?'房间口令（选填）':'口令（房主未设置可留空）'}<input name="passcode" id="room-passcode" type="password" inputmode="numeric" pattern="[0-9]{4,8}" maxlength="8" autocomplete="off" value="${E(c.fields.passcode||'')}"><small>${creating?'4—8位数字；不设口令时，知道房号的人都能加入。':'口令不放在分享链接中，向房主单独索取。'}</small></label><button class="btn primary" type="submit" ${busy?'disabled':''}>${busy?'正在连接…':creating?'创建房间，邀请朋友':'加入这桌'}</button><p id="room-entry-message" class="room-feedback" role="status">${E(c.client.message)}</p>${c.client.status==='error'&&!c.client.restoreAttempted?roomButton('重试恢复刚才的房间','resume','','btn ghost'):''}${policy()}</form></section><aside class="room-welcome"><div><span>01</span><h2>各自勾选想吃的</h2><p>谁想吃哪道，一眼看清。每道只进菜单一次，不按人数重复加份。</p></div><div><span>02</span><h2>各自认领能带的</h2><p>食材、工具和燃料分开勾。取消自己的勾选，不会删掉朋友的。</p></div><div><span>03</span><h2>一起凑成这顿饭</h2><p>汇总大家的物资找可做菜，房主统一调整人数和每道份量。</p></div></aside></div>`;
}
function scope(c) {
  return `<details class="room-filter" data-room-keep="filters"><summary>菜类筛选 · ${E(c.scope.length?c.scope.join('、'):'全部菜谱')}</summary><div class="room-scope"><span>按菜类筛选 <small>只影响你看到的候选，可多选</small></span><div class="chips" role="group" aria-label="房间菜谱分类">${roomButton('全部','scope',`data-id="" aria-pressed="${!c.scope.length}"`,`chip ${!c.scope.length?'active':''}`)}${c.index.categories.map(cat=>roomButton(E(cat),'scope',`data-id="${E(cat)}" aria-pressed="${c.scope.includes(cat)}"`,`chip ${c.scope.includes(cat)?'active':''}`)).join('')}</div></div></details>`;
}
function vote(c,r) {
  const mine=ownMember(c.room).choices.votes.includes(r.id), voters=c.room.members.filter(m=>m.choices.votes.includes(r.id));
  return `<div class="room-vote-line"><span>${voters.length?E(voters.slice(0,2).map(m=>m.nickname).join('、'))+(voters.length>2?`等${voters.length}人`:'')+'想吃':'还没有人点'}</span>${roomButton(mine?'✓ 已点':'＋ 我想吃','vote',`data-id="${E(r.id)}" aria-pressed="${mine}"`,mine?'btn selected':'btn')}</div>`;
}
function dishGrid(c,recipes,matches) {
  const p=paginate(recipes,c.page);
  return `<p class="room-result-count" role="status">${recipes.length} 道 · 本页 ${p.first}—${p.last}</p><div class="room-dish-grid">${p.items.map(r=>{const m=matches.get(r.id);return `<article class="room-dish"><button class="room-dish-image" type="button" data-room-action="detail" data-id="${E(r.id)}" aria-label="查看${E(r.title)}做法">${photoHTML(c.photos,r.id)}</button><div class="room-dish-content"><span class="eyebrow">${E(r.category)} · 约${r.totalMinutes}分钟</span><button class="room-dish-title" type="button" data-room-action="detail" data-id="${E(r.id)}"><h3>${E(r.title)}</h3></button><p class="room-readiness ${m?.ready?'ready':''}">${m?.ready?'✓ 大家的食材与工具已凑齐':`尚缺 ${m?.missingIngredients.length||0} 种食材${m?.missingTools.length?' · 缺工具':''}${m?.needsFreezer?' · 缺冷冻条件':''}`}</p>${vote(c,r)}</div></article>`;}).join('')||'<div class="empty"><h3>暂时没有匹配的菜</h3><p>减少筛选条件，或让朋友勾选能带的物资。</p></div>'}</div>${p.pages>1?`<nav class="pagination" aria-label="房间菜谱分页">${roomButton('上一页','page',`data-page="${p.page-1}" ${p.page===1?'disabled':''}`)}<span>${p.page} / ${p.pages}</span>${roomButton('下一页','page',`data-page="${p.page+1}" ${p.page===p.pages?'disabled':''}`)}</nav>`:''}`;
}
function dishesView(c) {
  const matches=matchInventory(c.index,{...c.room.inventory,categories:c.scope},{hasFreezer:c.room.hasFreezer});
  const byId=new Map(matches.map(m=>[m.recipe.id,m]));
  let recipes=searchEntries(c.index,{categories:c.scope,query:c.query});
  if(c.readyOnly)recipes=recipes.filter(r=>byId.get(r.id)?.ready);
  return `${scope(c)}<div class="room-search"><label class="search-box"><span aria-hidden="true">⌕</span><input type="search" id="room-dish-search" value="${E(c.query)}" placeholder="搜菜名、食材、苹果木" aria-label="搜索房间菜谱"></label><label class="check-inline"><input type="checkbox" id="room-ready-only" ${c.readyOnly?'checked':''}>只看大家凑齐的</label></div>${dishGrid(c,recipes,byId)}<p class="quantity-note">“凑齐”只核对种类和工具，不代表数量足够。实拍图片为同类参考；做法和保存条件以操作卡为准。</p>`;
}
function suppliesView(c) {
  const candidates=inventoryCandidates(c.index,c.scope,c.supplyQuery), me=ownMember(c.room);
  const kind=c.supplyKind, items=candidates[kind], groups=[...new Set(items.map(i=>i.group))];
  return `${scope(c)}<div class="room-supply-intro"><div><h2>勾选我能带的</h2><p>下面的勾选只属于你。朋友带的会显示在名称旁边。</p></div>${roomButton('带入我的个人库存','import-own','','btn ghost')}</div><div class="room-supply-tools"><div class="room-segments" role="group" aria-label="物资类型">${[['ingredients','食材'],['tools','工具与燃料']].map(([k,l])=>roomButton(l,'supply-kind',`data-value="${k}" aria-pressed="${kind===k}"`,kind===k?'active':'')).join('')}</div><label class="search-box"><input type="search" id="room-supply-search" aria-label="搜索房间物资" placeholder="找食材、竹炭、苹果木…" value="${E(c.supplyQuery)}"></label></div><div class="room-supply-groups">${groups.map((group,index)=>`<details class="room-supply-group" data-room-keep="${E(kind+group)}" ${index===0||c.supplyQuery?'open':''}><summary>${E(group)} <small>${items.filter(x=>x.group===group&&me.choices[kind].includes(x.id)).length} / ${items.filter(x=>x.group===group).length} 我能带</small></summary><div>${items.filter(i=>i.group===group).map(i=>{const owners=c.room.members.filter(m=>m.choices[kind].includes(i.id));const mine=me.choices[kind].includes(i.id);return `<label class="room-supply-item ${mine?'is-owned':''}"><input type="checkbox" data-room-kind="${kind==='ingredients'?'ingredient':'tool'}" data-id="${E(i.id)}" ${mine?'checked':''}><span><b>${E(i.name)}</b><small>${owners.length?E(owners.map(m=>m.id===me.id?'我':m.nickname).join('、'))+' 带':'还没有人认领'}</small>${kind==='tools'&&i.note?`<small>${E(i.note)}</small>`:''}</span></label>`;}).join('')}</div></details>`).join('')||'<div class="empty">这个范围没有匹配物资。</div>'}</div><label class="room-freezer"><input type="checkbox" id="room-freezer" ${me.choices.hasFreezer?'checked':''}><span>我能提供持续≤-18℃冷冻条件<small>普通保冷箱或冷藏模式不算冷冻。</small></span></label>`;
}
function menuView(c) {
  const plan=roomPlan(c.room,c.db),host=c.room.host===c.room.memberId;
  return `<div class="room-menu-heading"><div><h2>这桌想吃 ${plan.views.length} 道</h2><p>参与人数不等于用餐人数；想吃票数不增加份量。</p></div><label class="room-people">用餐人数 <input type="number" id="room-people" min="1" max="16" step="1" value="${c.room.settings.people}" ${!host?'disabled':''}> 人</label></div><p class="quantity-note">${host?'你是房主，可以调整人数、份量和出餐顺序。':'人数、份量和出餐顺序由房主统一调整。'}</p>${plan.views.length?`<div class="room-menu-list">${plan.views.map((r,n)=>`<article class="room-menu-dish"><div><button type="button" class="room-dish-title" data-room-action="detail" data-id="${E(r.id)}"><h3>${n+1}. ${E(r.title)}</h3></button>${vote(c,r)}</div><div class="room-menu-controls"><label>每道份量 <select data-room-portion="${E(r.id)}" ${!host?'disabled':''}>${[.25,.5,.75,1,1.5,2,3,4].map(v=>`<option value="${v}" ${v===(c.room.settings.portions[r.id]??1)?'selected':''}>${v===.5?'半份':v+'份'}</option>`).join('')}</select></label>${host?`${roomButton('↑','move',`data-id="${E(r.id)}" data-delta="-1" ${n===0?'disabled':''} aria-label="上移${E(r.title)}"`,'round-btn')}${roomButton('↓','move',`data-id="${E(r.id)}" data-delta="1" ${n===plan.views.length-1?'disabled':''} aria-label="下移${E(r.title)}"`,'round-btn')}`:''}</div></article>`).join('')}</div><section class="room-shopping panel"><div class="section-head"><h2>合计要带多少</h2>${roomButton('导出这桌清单','export','','btn primary')}</div><p class="quantity-note">数量是合计净需求；认领某种食材不等于认领全部数量。请线下核对谁带多少。</p><div class="room-shopping-grid">${plan.shopping.map(item=>{const providers=c.room.members.filter(m=>m.choices.ingredients.includes(item.id));return `<div><b>${E(item.name)}</b><strong>${formatQty(item.qty,item.unit)}</strong><small class="${providers.length?'':'unclaimed'}">${providers.length?E(providers.map(m=>m.nickname).join('、'))+' 能带':'待采购 / 认领'}</small></div>`;}).join('')}</div></section><details class="panel"><summary>工具、冷链和搭配提醒</summary><p>${E(plan.equipment.join('、'))}</p>${plan.issues.map(x=>`<p><b>${E(x.title)}</b>：${E(x.detail)}</p>`).join('')}<p>本次过敏原：${E(plan.allergens.join('、')||'仍需查看商品标签')}。生熟分开，按做法检查安全熟度。</p></details>`:'<div class="empty"><h3>先挑一道大家想吃的</h3><p>到“点菜”勾选“我想吃”，就会合并到这张菜单。</p>'+roomButton('去点菜','pane','data-value="dishes"','btn primary')+'</div>'}`;
}
export function workspaceView(c) {
  const me=ownMember(c.room),state=c.client.status, status={synced:'已同步',saving:`${c.client.pending.length}项正在保存`,offline:'连接中断 · 保留待同步选择',conflict:'有未同步的选择',joining:'正在连接'}[state]||state;
  const members=`<details class="room-members" data-room-keep="members"><summary>${c.room.members.length}人参与 <span>查看成员</span></summary><div>${c.room.members.map(m=>`<article><span class="room-avatar" aria-hidden="true">${E(Array.from(m.nickname)[0])}</span><div><b>${E(m.nickname)}${m.id===c.room.host?' · 房主':''}${m.id===me.id?' · 我':''}</b><small>想吃${m.choices.votes.length}道 · 能带${m.choices.ingredients.length}种食材、${m.choices.tools.length}项工具</small></div></article>`).join('')}</div></details>`;
  return `<section class="room-workspace"><header class="room-header"><div><h1>房间 <span class="room-number">${E(c.room.number)}</span></h1><p>${E(me.nickname)}${c.room.host===me.id?' · 房主':''} <span>｜ ${dateLabel(c.room.expiresAt)} 关闭${c.room.locked?' · 已设口令':''}</span></p></div><div class="actions">${roomButton('邀请朋友','share','','btn primary')}${roomButton('退出房间','leave','','btn ghost')}</div></header><div class="room-sync ${state==='synced'?'synced':state==='saving'?'saving':'attention'}"><span role="status" aria-live="polite">${E(status)}</span>${members}${state!=='synced'&&c.client.message?`<span>${E(c.client.message)}</span>`:''}${c.client.blocked?`<ul class="room-conflicts">${c.client.pending.slice(0,6).map(op=>{const name=op.kind==='people'?'用餐人数':op.kind==='order'?'出餐顺序':op.key?(c.db.ingredients[op.key]?.name||c.db.recipes.find(r=>r.id===op.key)?.title||c.index.tools?.get?.(op.key)?.name||op.key):'冷冻条件';const fmt=v=>typeof v==='boolean'?(v?'已选':'未选'):Array.isArray(v)?'已调整顺序':String(v);return `<li>${E(name)}：服务器 ${E(fmt(operationValue(c.client.room,op)))}，本机待提交 ${E(fmt(op.value))}</li>`;}).join('')}</ul><div>${roomButton('核对后按我的选择提交','resolve-mine','','btn')}${roomButton('放弃待同步修改','resolve-server','','btn ghost')}</div>`:''}${!c.client.storageOK?'<span>浏览器无法保留待同步操作，请保持此页打开直到显示“已同步”。</span>':''}</div>${c.shareOpen?`<section class="room-share panel"><label>把房号或链接发给朋友<input id="room-share-link" type="text" readonly value="${E(location.origin+location.pathname+'#rooms/'+c.room.number)}"></label><p>${c.room.locked?'口令请单独发送，链接不包含口令。':'未设口令，知道房号的人可以加入。'}</p>${roomButton('复制邀请','copy','','btn')}${roomButton('收起','share','','text-btn')}</section>`:''}<nav class="room-panes" aria-label="房间功能">${[['dishes','点菜'],['supplies','我能带的'],['menu',`这桌菜单 · ${c.room.selected.length}`]].map(([v,l])=>roomButton(l,'pane',`data-value="${v}" ${c.pane===v?'aria-current="page"':''}`,c.pane===v?'active':'')).join('')}</nav><div id="room-pane-content">${c.pane==='supplies'?suppliesView(c):c.pane==='menu'?menuView(c):dishesView(c)}</div><p class="room-note" id="room-action-note" role="status">${E(c.note)}</p><details class="room-archive-note"><summary>七天后会怎样？</summary>${policy()}<p>到期后网页不会查询GitHub来恢复房间。归档遇到网络故障会在服务器重试，但不会延长房间有效期。</p></details></section>`;
}
export function roomRecipeHTML(c,id) {
  const r=recipeView(c.db,id,{...defaultState(),people:c.room.settings.people,portions:c.room.settings.portions});
  return `<div class="dialog-header"><div><span class="eyebrow">房间 ${E(c.room.number)} · ${c.room.settings.people}人 × ${r.portion}份</span><h2 id="room-recipe-title">${E(r.title)}</h2></div>${roomButton('×','close-recipe','aria-label="关闭房间做法"','close-btn')}</div><div class="dialog-body"><section class="fire-instruction"><h3>火怎么摆</h3><p>${E(r.fireSetup||r.smoke)}</p></section><h3>这道用量</h3><div class="ingredient-lines">${r.rows.map(i=>`<div><b>${E(i.name)}</b><strong>${formatQty(i.qty,i.unit)}</strong></div>`).join('')}</div><h3 class="section-title">提前准备</h3>${r.prep.map(t=>`<p>${E(t)}</p>`).join('')}<h3 class="section-title">上火做法</h3><ol class="room-recipe-steps">${r.steps.map(s=>`<li>${E(s)}</li>`).join('')}</ol><section class="doneness"><h3>什么时候算做好</h3><p>${E(r.completion||r.tip)}</p></section><h3>怎么吃</h3><p>${E(r.serving||r.fun)}</p><details class="panel"><summary>工具与保存</summary><p>${E(r.equipment.join('、'))}</p><p>${E(r.hold)}</p></details></div><div class="dialog-footer">${vote(c,r)}${roomButton('关闭','close-recipe','','btn ghost')}</div>`;
}
